name: Checkout speckle-bundle-spec
description: Checkout speckle-bundle-spec

inputs: 
   token:
     required: true
     description: "GitHub Auth Token"
     
runs:
  using: "composite"
  steps:
    - name: Checkout speckle-bundle-spec
      uses: actions/checkout@v7
      with:
        repository: specklesystems/speckle-bundle-spec
        ref: a980a8eb0354307d9e1ff18fee4ed93b7558cc61
        token: ${{ inputs.token }}
        path: speckle-bundle-spec
        persist-credentials: false
