name: Checkout speckle-bundle-spec
description: Checkout speckle-bundle-spec

inputs: 
   token:
     required: true
     description: "GitHub Auth Token"
     
runs:
  using: "composite"
  steps:
    - name: Checkout speckle-bundle-spec
      uses: actions/checkout@v7
      with:
        repository: specklesystems/speckle-bundle-spec
        ref: 1f52b05f77e53822870c9097f911c764ce1c5198
        token: ${{ inputs.token }}
        path: speckle-bundle-spec
        persist-credentials: false
