name: Checkout speckle-bundle-spec
description: Checkout speckle-bundle-spec

inputs: 
   token:
     required: true
     description: "GitHub Auth Token"
     
runs:
  using: "composite"
  steps:
    - name: Checkout speckle-bundle-spec
      uses: actions/checkout@v7
      with:
        repository: specklesystems/speckle-bundle-spec
        ref: 72c6a78ef48465f401c8a5ae61517abbf0b8b906
        token: ${{ inputs.token }}
        path: speckle-bundle-spec
        persist-credentials: false
